version: "3.8"
services:
  sshd:
    container_name: sshd
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2200:22"
    environment:
      SSH_USER: user # Required
    volumes:
      - ./keys:/etc/ssh/keys # Required, add your authorized_keys file there, the newly generated host keys will be saved here as well
